config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins
  get 'welcome/index'

   root 'welcome#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :photo, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except:[:index, :show]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description , :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agua</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
	

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'shared/navbar'%>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
	
<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
        <div class="field">
          <%= f.label :name ,"nombre"%><br>
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
    </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :photo ,"foto" %><br>
      <%= f.text_field :photo, :class => 'form-control', :placeholder => "ingresa una url de imagen" %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :description ,"descripcion"%><br>
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
  </div>
   
      <div class="actions">
        <%= f.submit "Crear", :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
 <div class="row">
 	<div class="col-md-6">
		<h1>Editing Pin</h1>
		<%= render 'form' %>
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
 </div>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>IMAGENES</h1>
<div class="container">
  <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img-responsive') %>
        <%= pin.description %>
        <div class="buttons" style="margin-top:10px; margin-botton:10px">
          <%= link_to 'Show', pin, :class => 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } ,:class => 'btn' %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>HOla ingresa la direccion de una imagen</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
	<p><%= link_to 'Back', pins_path %></p>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>nombre:</strong>
  <%= @pin.name %>
</p>
<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width:500px')  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">pinterest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= pins_path %>">PINS <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
        <li><a href="<%= new_user_session_path %>"> Ingreso </a></li>
        <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
        <% else %>
        <li><a href="<%= destroy_user_session_path %>" data-method="delete"> Salir </a></li>
        <% end %>
      </ul>    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
 <div class="container">
  <h1>mandarino</h1>
  <p>...</p>
  <p><a class=" btn btn-success " href="<%= new_pin_path %>" role="button"> apretame <span class="glyphicon glyphicon-heart-empty"  style="color:orange"></span></a></p>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col-md-4">
    <div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>
      <a href="www.google.cl" target="_bank">google</a>
      <p class="titulos">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus voluptas tempora recusandae dolorum minima porro et quo molestiae enim necessitatibus, voluptatibus, officia odit quasi vero quisquam laboriosam dignissimos! Repudiandae, alias.
      </p>
    </div>
    <div class="col-md-4">
    <div class="page-header">
  <h1 style="display:inline">Example page </h1>
  <span class="label label-default">New</span>
</div>
      <a href="www.google.cl" target="_bank">google</a>
      <p class="titulos">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus voluptas tempora recusandae dolorum minima porro et quo molestiae enim necessitatibus, voluptatibus, officia odit quasi vero quisquam laboriosam dignissimos! Repudiandae, alias.
      </p>
      <img src="http://www.wikinoticia.com/images2//monkeyzen.hipertextual.netdna-cdn.com/files/2012/11/GIF-dinosaurios.gif" style="width:500px" style="align:center">
    </div>
     <div class="col-md-4">
     <div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>
      <a href="www.google.cl" target="_bank">google</a>
      <p class="titulos">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus voluptas tempora recusandae dolorum minima porro et quo molestiae enim necessitatibus, voluptatibus, officia odit quasi vero quisquam laboriosam dignissimos! Repudiandae, alias.
      </p>
    </div>
</div>
</div>